name = "test-new"
type = "webpack"
account_id = "2c2eae7c46fdef478ca007471a296695"
workers_dev = true
zone_id = "fec2bdb9b6cb3f5f0de71ec2208c999c"
route = "https://test-new.santosh-2c2.workers.dev/*"
compatibility_date = "2024-07-05"

kv_namespaces = [
  { binding = "KEY_KV", id = "123456789" }
]

[site]
bucket = "./build/dist"
entry-point = "workers-site"

[build]
# Define custom headers for specific file types
[[build.headers]]
match = "*.css"
headers = { Content-Type = "text/css" }
